"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./facebook-content-scheduler.module.css";

type Post = { id:string; title:string; contentType:string; body:string; mediaUrl:string|null; status:string; creativeVersion:number; creativeGeneratedAt:string|null };
type FacebookStatus = { configured:boolean; oauthConfigured:boolean; connected:boolean; targetPageName:string; pageId:string|null; pageName:string|null; source:string|null };
type Publication = { id:string; postId:string; status:string; scheduledAt:string|null; publishedAt:string|null; facebookPostId:string|null; failureReason:string|null; createdAt:string };
type PublishingHealth = { facebookConnected:boolean; pageReachable:boolean; pageError:string|null; cronConfigured:boolean; fallbackDueCount:number; oldestFallbackDueAt:string|null; primarySchedulingMode:string };

function defaultLocalTime(){const d=new Date(Date.now()+15*60*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}

export function FacebookContentScheduler(){
  const [posts,setPosts]=useState<Post[]>([]);const [facebook,setFacebook]=useState<FacebookStatus|null>(null);const [health,setHealth]=useState<PublishingHealth|null>(null);const [publications,setPublications]=useState<Publication[]>([]);const [times,setTimes]=useState<Record<string,string>>({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const [a,b,c,h]=await Promise.all([fetch("/api/admin/content",{cache:"no-store"}),fetch("/api/admin/facebook/status",{cache:"no-store"}),fetch("/api/admin/facebook/publications",{cache:"no-store"}),fetch("/api/admin/facebook/publishing-health",{cache:"no-store"})]);const [content,status,pubs,healthData]=await Promise.all([a.json(),b.json(),c.json(),h.json()]);if(!a.ok)throw new Error(content.error||"Unable to load approved content.");if(!b.ok)throw new Error(status.error||"Unable to check Facebook connection.");if(!c.ok)throw new Error(pubs.error||"Unable to load Facebook schedule.");if(!h.ok)throw new Error(healthData.error||"Unable to check publishing health.");setPosts((Array.isArray(content.posts)?content.posts:[]).filter((p:Post)=>p.status==="APPROVED"));setFacebook(status);setHealth(healthData);setPublications(Array.isArray(pubs.publications)?pubs.publications:[]);setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to load Facebook Scheduler.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{const result=new URLSearchParams(window.location.search).get("facebook");if(result==="connected")setNotice("MedMinds Learning Centre is connected to the Sales Agent.");if(result==="page-not-found")setError("The authorized account did not return a managed Page named MedMinds Learning Centre.");if(result==="connection-failed")setError("Facebook authorization could not be completed. Please connect again and approve the requested Page permissions.");if(result==="setup-required")setError("Facebook authorization needs the Meta app credentials configured on the Sales Agent first.");},[]);
  const latest=useMemo(()=>{const map=new Map<string,Publication>();for(const p of publications)if(!map.has(p.postId))map.set(p.postId,p);return map;},[publications]);

  async function schedule(post:Post){const when=new Date(times[post.id]||defaultLocalTime());if(Number.isNaN(when.getTime())){setError("Choose a valid date and time.");return;}if(when.getTime()<Date.now()+10*60*1000){setError("Choose a time at least 10 minutes from now so Facebook can register the scheduled Page post.");return;}setBusy(post.id);setError("");setNotice("");try{const r=await fetch(`/api/admin/content/${post.id}/schedule-facebook`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scheduledAt:when.toISOString()})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to schedule this Facebook post.");setNotice(`Scheduled “${post.title}” directly with Facebook for ${when.toLocaleString()}. Facebook now owns the delivery time; the exact approved caption and image are frozen.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to schedule post.");}finally{setBusy("");}}
  async function postNow(post:Post){if(!window.confirm(`Post “${post.title}” to MedMinds Learning Centre now? The approved caption and image will be published immediately.`))return;setBusy(post.id);setError("");setNotice("");try{const r=await fetch(`/api/admin/content/${post.id}/publish-facebook`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to publish this Facebook post.");setNotice(`Published “${post.title}” to MedMinds Learning Centre now.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to publish post.");}finally{setBusy("");}}
  async function processDue(){if(!window.confirm("Publish all overdue legacy Facebook items now? Only items that were queued locally and never registered with Facebook will be processed."))return;setBusy("due");setError("");setNotice("");try{const r=await fetch("/api/admin/facebook/process-due",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to process overdue posts.");const published=Array.isArray(d.results)?d.results.filter((x:{status:string})=>x.status==="published").length:0;const failed=Array.isArray(d.results)?d.results.filter((x:{status:string})=>x.status==="failed").length:0;setNotice(`Overdue queue processed: ${published} published${failed?`, ${failed} failed`:""}.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to process overdue posts.");}finally{setBusy("");}}
  async function cancel(post:Post){if(!window.confirm(`Cancel the Facebook schedule for “${post.title}”?`))return;setBusy(post.id);setError("");setNotice("");try{const r=await fetch(`/api/admin/content/${post.id}/schedule-facebook`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to cancel schedule.");setNotice(`Facebook schedule cancelled for “${post.title}”.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to cancel schedule.");}finally{setBusy("");}}

  return <main className={styles.page}><div className={styles.shell}>
    <header className={styles.topbar}><div><Link className={styles.back} href="/admin">← Sales Agent dashboard</Link><span className={styles.eyebrow}>MedMinds social publishing</span><h1>Facebook Scheduler</h1><p>Publish immediately or register a future Page post directly with Facebook. Approved captions and creatives are frozen before delivery.</p></div><Link className={styles.studioLink} href="/admin/content">Open Content Studio</Link></header>
    {(error||notice)&&<div className={error?styles.error:styles.notice}>{error||notice}</div>}
    <section className={`${styles.connection} ${facebook?.connected&&health?.pageReachable?styles.connected:""}`}><div className={styles.connectionInfo}><span className={styles.statusDot}/><div><h2>{facebook?.pageName||facebook?.targetPageName||"MedMinds Learning Centre"}</h2><p>{facebook?.connected?(health?.pageReachable?"Connected and verified for direct and scheduled Facebook publishing.":`Connected, but Facebook publishing needs attention${health?.pageError?`: ${health.pageError}`:"."}`):"Connect the Page once, then approved content can be published from this workspace."}</p></div></div><div className={styles.connectionActions}>{!facebook?.connected&&facebook?.oauthConfigured&&<a className={styles.primary} href="/api/admin/facebook/connect">Connect Facebook Page</a>}<button className={styles.secondary} disabled={loading} onClick={()=>void load()}>Refresh</button></div></section>
    {facebook&&!facebook.connected&&!facebook.oauthConfigured&&<div className={styles.setup}><strong>One-time Meta app setup is required.</strong><p>Configure <code>META_FACEBOOK_APP_ID</code> and <code>META_FACEBOOK_APP_SECRET</code>, then register <code>https://sales.medmindslc.online/api/admin/facebook/callback</code> as a valid OAuth redirect URI. The connection is restricted to “{facebook.targetPageName}”.</p></div>}
    {health?.fallbackDueCount>0&&<div className={styles.setup}><strong>{health.fallbackDueCount} overdue legacy Facebook post{health.fallbackDueCount===1?" is":"s are"} waiting.</strong><p>The older scheduler saved these locally but the background worker did not process them. New schedules are sent directly to Facebook and no longer depend on that worker.</p><button className={styles.primary} disabled={Boolean(busy)} onClick={()=>void processDue()}>{busy==="due"?"Publishing…":"Publish overdue now"}</button></div>}
    <div className={styles.header}><div><span className={styles.eyebrow}>Approved content</span><h2>Ready to publish</h2></div><span>{posts.length} approved post{posts.length===1?"":"s"}</span></div>
    {loading?<div className={styles.empty}>Loading scheduler…</div>:posts.length===0?<div className={styles.empty}>No approved content is ready. <Link href="/admin/content">Create and approve a post in Content Studio.</Link></div>:<div className={styles.grid}>{posts.map(post=>{
      const publication=latest.get(post.id);const activePublication=publication&&publication.status!=="CANCELLED"?publication:null;const isBusy=busy===post.id;const hasCreative=Boolean(post.creativeGeneratedAt);const canPublish=Boolean(facebook?.connected&&health?.pageReachable&&hasCreative);const value=times[post.id]||defaultLocalTime();const imageSrc=activePublication?`/api/content/publication-image/${activePublication.id}`:hasCreative?`/api/content/creative/${post.id}?v=${post.creativeVersion||1}`:"";const nativeScheduled=activePublication?.status==="SCHEDULED"&&Boolean(activePublication.facebookPostId);
      return <article className={styles.card} key={post.id}><div className={styles.creative}>{imageSrc?<img src={imageSrc} alt={`${post.title} ${activePublication?"attached Facebook image":"approved creative"}`}/>:<div className={styles.noCreative}>Generate an image in Content Studio before publishing.</div>}</div><div className={styles.content}><div className={styles.meta}><span className={styles.type}>{post.contentType}</span>{hasCreative&&<span style={{fontSize:10,fontWeight:900,color:"#075548",background:"#dff3ec",padding:"5px 8px",borderRadius:999}}>✓ Image attached</span>}{activePublication&&<b className={`${styles.badge} ${activePublication.status==="SCHEDULED"?styles.scheduled:activePublication.status==="PUBLISHED"?styles.published:activePublication.status==="FAILED"?styles.failed:""}`}>{nativeScheduled?"SCHEDULED ON FACEBOOK":activePublication.status}</b>}</div><h3>{post.title}</h3><p className={styles.caption}>{post.body}</p>{activePublication&&<div className={`${styles.publication} ${activePublication.status==="FAILED"?styles.failure:""}`}>{activePublication.status==="SCHEDULED"&&activePublication.scheduledAt&&<>{nativeScheduled?"Registered directly with Facebook":"Legacy local queue"} for {new Date(activePublication.scheduledAt).toLocaleString()}. The image shown above is the frozen attachment.</>}{activePublication.status==="PUBLISHED"&&<>Published {activePublication.publishedAt?new Date(activePublication.publishedAt).toLocaleString():""} with the attached image.</>}{activePublication.status==="FAILED"&&<>Publishing failed: {activePublication.failureReason||"Unknown Facebook error."}</>}</div>}
      <div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0"}}><Link href={`/admin/content/${post.id}/image-editor`} style={{textDecoration:"none",fontSize:12,fontWeight:900,color:"#0d725f",border:"1px solid #b9d9d1",background:"#f2faf7",padding:"8px 10px",borderRadius:9}}>{nativeScheduled?"Edit next version":"Edit image manually"}</Link><Link href={`/admin/content/${post.id}/canva`} style={{textDecoration:"none",fontSize:12,fontWeight:900,color:"#7d2ae8",border:"1px solid #d8c2f6",background:"#faf7ff",padding:"8px 10px",borderRadius:9}}>Edit / template in Canva</Link></div>
      <div className={styles.controls}><label className={styles.dateLabel}>Schedule date & time<input type="datetime-local" value={value} onChange={e=>setTimes(current=>({...current,[post.id]:e.target.value}))}/><small style={{display:"block",marginTop:5,color:"#687b77"}}>At least 10 minutes from now.</small></label><div className={styles.actions}><button className={styles.primary} disabled={!canPublish||isBusy||nativeScheduled} onClick={()=>void postNow(post)}>{isBusy?"Working…":activePublication?.status==="FAILED"?"Retry now":"Post now"}</button><button className={styles.secondary} disabled={!canPublish||isBusy} onClick={()=>void schedule(post)}>{isBusy?"Working…":nativeScheduled?"Reschedule":"Schedule"}</button>{activePublication?.status==="SCHEDULED"&&<button className={styles.danger} disabled={isBusy} onClick={()=>void cancel(post)}>Cancel schedule</button>}</div></div></div></article>;
    })}</div>}
    <p className={styles.footnote}>New schedules are registered with Facebook immediately, so the post no longer waits for a Vercel cron at publish time. The legacy worker remains as a fallback and recovery mechanism.</p>
  </div></main>;
}
