type ManagementBriefExportInput = {
  analysis: string;
  generatedAt?: string | null;
  days?: number | null;
};

type BriefLine = { kind: "heading" | "bullet" | "numbered" | "paragraph"; text: string };

function cleanInline(value: string) {
  return value
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/[`*_#]/g, "")
    .replace(/[–—]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

export function parseManagementBrief(value: string): BriefLine[] {
  const result: BriefLine[] = [];
  for (const raw of value.replace(/\r/g, "").split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    const heading = line.match(/^#{1,4}\s+(.+)$/);
    if (heading) { result.push({ kind: "heading", text: cleanInline(heading[1]) }); continue; }
    const numbered = line.match(/^\d+[.)]\s+(.+)$/);
    if (numbered) { result.push({ kind: "numbered", text: cleanInline(numbered[1]) }); continue; }
    const bullet = line.match(/^[-*•]\s+(.+)$/);
    if (bullet) { result.push({ kind: "bullet", text: cleanInline(bullet[1]) }); continue; }
    result.push({ kind: "paragraph", text: cleanInline(line) });
  }
  return result;
}

function safePdfText(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function pdfLine(text: string, x: number, y: number, size = 10.5, font = "F1", color = "0.13 0.23 0.31") {
  return `BT /${font} ${size} Tf ${color} rg 1 0 0 1 ${x} ${y} Tm (${safePdfText(text)}) Tj ET`;
}

function wrap(text: string, width: number) {
  const words = cleanInline(text).split(/\s+/).filter(Boolean);
  const rows: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (current && next.length > width) { rows.push(current); current = word; }
    else current = next;
  }
  if (current) rows.push(current);
  return rows.length ? rows : [""];
}

function dateLabel(value?: string | null) {
  const date = value ? new Date(value) : new Date();
  return Number.isFinite(date.getTime())
    ? date.toLocaleString("en-ZM", { day: "2-digit", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit" })
    : "Generated by MedMinds";
}

function buildSimpleMultiPagePdf(pageContents: string[]) {
  const pages = pageContents.length ? pageContents : [""];
  const pageCount = pages.length;
  const font1Id = 3 + pageCount * 2;
  const font2Id = font1Id + 1;
  const objects: Buffer[] = [];
  objects.push(Buffer.from("<< /Type /Catalog /Pages 2 0 R >>", "utf8"));
  const kids = pages.map((_, index) => `${3 + index * 2} 0 R`).join(" " );
  objects.push(Buffer.from(`<< /Type /Pages /Kids [${kids}] /Count ${pageCount} >>`, "utf8"));
  pages.forEach((content, index) => {
    const contentId = 4 + index * 2;
    objects.push(Buffer.from(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font1Id} 0 R /F2 ${font2Id} 0 R >> >> /Contents ${contentId} 0 R >>`, "utf8"));
    const bytes = Buffer.from(content, "utf8");
    objects.push(Buffer.concat([Buffer.from(`<< /Length ${bytes.length} >>\nstream\n`, "utf8"), bytes, Buffer.from("\nendstream", "utf8")]));
  });
  objects.push(Buffer.from("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", "utf8"));
  objects.push(Buffer.from("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>", "utf8"));

  const header = Buffer.from("%PDF-1.4\n%MedMinds\n", "utf8");
  const chunks: Buffer[] = [header];
  const offsets: number[] = [0];
  let position = header.length;
  objects.forEach((object, index) => {
    const prefix = Buffer.from(`${index + 1} 0 obj\n`, "utf8");
    const suffix = Buffer.from("\nendobj\n", "utf8");
    offsets.push(position);
    chunks.push(prefix, object, suffix);
    position += prefix.length + object.length + suffix.length;
  });
  const xrefOffset = position;
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets.slice(1)) xref += `${String(offset).padStart(10, "0")} 00000 n \n`;
  xref += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  chunks.push(Buffer.from(xref, "utf8"));
  return Buffer.concat(chunks);
}

export function createManagementBriefPdf(input: ManagementBriefExportInput) {
  const blocks = parseManagementBrief(input.analysis);
  const navy = "0.071 0.247 0.302";
  const teal = "0.055 0.529 0.494";
  const muted = "0.39 0.47 0.46";
  const pageWidth = 595;
  const pageHeight = 842;
  const left = 46;
  const right = 549;
  const pages: string[][] = [];
  let content: string[] = [];
  let y = 680;
  let orderedIndex = 0;

  const startPage = () => {
    content = [
      "q",
      "1 1 1 rg 0 0 595 842 re f",
      pdfLine("MEDMINDS LEARNING CENTRE", 46, 789, 9.5, "F2", teal),
      pdfLine("Business Intelligence", 46, 766, 16, "F2", navy),
      `${navy} rg 0 744 ${pageWidth} 4 re f`,
      `${teal} rg 0 740 ${pageWidth} 4 re f`,
      pdfLine("MANAGEMENT BRIEF", 46, 710, 8.5, "F2", teal),
      pdfLine("Management brief", 46, 684, 20, "F2", navy),
      pdfLine(input.days ? `${input.days}-day analysis · ${dateLabel(input.generatedAt)}` : dateLabel(input.generatedAt), 46, 664, 8.7, "F1", muted),
      "0.88 0.92 0.91 RG 0.7 w 46 646 m 549 646 l S"
    ];
    y = 621;
  };

  const finishPage = () => {
    const pageNumber = pages.length + 1;
    content.push(
      "0.88 0.92 0.91 RG 0.7 w 46 48 m 549 48 l S",
      pdfLine("MedMinds Learning Centre · Business Intelligence", 46, 31, 7.8, "F1", muted),
      pdfLine(`Page ${pageNumber}`, 510, 31, 7.8, "F1", muted),
      "Q"
    );
    pages.push(content);
  };

  const ensureSpace = (needed: number) => {
    if (y - needed >= 64) return;
    finishPage();
    startPage();
  };

  startPage();
  for (const block of blocks) {
    if (block.kind === "heading") {
      orderedIndex = 0;
      const rows = wrap(block.text, 66);
      ensureSpace(26 + rows.length * 16);
      y -= 4;
      content.push(pdfLine(rows[0], left, y, 12.5, "F2", navy));
      y -= 17;
      for (const row of rows.slice(1)) { content.push(pdfLine(row, left, y, 12.5, "F2", navy)); y -= 17; }
      content.push(`${teal} rg ${left} ${y + 6} 44 1.6 re f`);
      y -= 9;
      continue;
    }

    if (block.kind === "numbered") orderedIndex += 1;
    const prefix = block.kind === "bullet" ? "- " : block.kind === "numbered" ? `${orderedIndex}. ` : "";
    const indent = block.kind === "paragraph" ? left : left + 12;
    const width = block.kind === "paragraph" ? 86 : 80;
    const rows = wrap(block.text, width);
    ensureSpace(rows.length * 14 + 10);
    rows.forEach((row, index) => {
      const lineText = index === 0 ? `${prefix}${row}` : row;
      content.push(pdfLine(lineText, indent + (index ? 10 : 0), y, 9.8, "F1", block.kind === "paragraph" ? "0.20 0.31 0.34" : "0.13 0.28 0.31"));
      y -= 14;
    });
    y -= block.kind === "paragraph" ? 6 : 4;
  }
  finishPage();
  return buildSimpleMultiPagePdf(pages.map((page) => page.join("\n")));
}

function escapeHtml(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function inlineHtml(value: string) {
  const escaped = escapeHtml(value);
  return escaped.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
}

export function createManagementBriefWord(input: ManagementBriefExportInput) {
  const lines = input.analysis.replace(/\r/g, "").split("\n");
  const html: string[] = [];
  let list: "ul" | "ol" | null = null;
  const closeList = () => { if (list) html.push(`</${list}>`); list = null; };

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) { closeList(); continue; }
    const heading = line.match(/^#{1,4}\s+(.+)$/);
    if (heading) { closeList(); html.push(`<h2>${inlineHtml(heading[1])}</h2>`); continue; }
    const numbered = line.match(/^\d+[.)]\s+(.+)$/);
    const bullet = line.match(/^[-*•]\s+(.+)$/);
    if (numbered || bullet) {
      const kind: "ul" | "ol" = numbered ? "ol" : "ul";
      if (list !== kind) { closeList(); list = kind; html.push(`<${kind}>`); }
      html.push(`<li>${inlineHtml((numbered || bullet)![1])}</li>`);
      continue;
    }
    closeList();
    html.push(`<p>${inlineHtml(line)}</p>`);
  }
  closeList();

  const title = input.days ? `${input.days}-day management brief` : "Management brief";
  return `<!doctype html><html><head><meta charset="utf-8"><title>MedMinds ${escapeHtml(title)}</title><style>
    @page{size:A4;margin:22mm 19mm} body{font-family:Arial,Helvetica,sans-serif;color:#203952;font-size:10.5pt;line-height:1.55} .brand{border-bottom:4px solid #12877e;padding-bottom:12px;margin-bottom:24px}.brand h1{margin:0;font-size:22pt;color:#123f4d}.brand p{margin:5px 0 0;color:#64766f;font-size:9.5pt}h2{font-size:13.5pt;color:#123f4d;margin:20px 0 7px;border-top:1px solid #e3ece9;padding-top:12px}h2:first-of-type{border-top:0;padding-top:0}p{margin:5px 0 10px}ul,ol{margin:6px 0 12px;padding-left:22px}li{margin:5px 0}strong{color:#12313b}.footer{margin-top:26px;border-top:1px solid #e3ece9;padding-top:9px;color:#70817b;font-size:8.5pt}</style></head><body><div class="brand"><h1>MedMinds Business Intelligence</h1><p>${escapeHtml(title)} · ${escapeHtml(dateLabel(input.generatedAt))}</p></div>${html.join("")}<div class="footer">Generated from the authenticated MedMinds Business Intelligence workspace.</div></body></html>`;
}
