export type ResearchCampaignOpening = {
  reply: string;
  serviceInterest: string;
};

const OTHER_SERVICE = /\b(pa\s*gym|osce|exam prep|tutorial|software|website|web development|automation|cybersecurity|workforce|logbook)\b/i;
const VAGUE_AD_ENQUIRY = /\b(more\s+info(?:rmation)?|info\s+on\s+this|tell\s+me\s+more|details(?:\s+please)?|how\s+does\s+this\s+work|i(?:'|’)?.?m\s+interested|interested\s+in\s+this|saw\s+your\s+ad|seen\s+your\s+ad|about\s+this|what\s+is\s+this|can\s+i\s+get\s+more)\b/i;
const SHORT_PRICE_ENQUIRY = /\b(how\s+much|price|cost|fee|charges?)\b/i;

/**
 * Handles the low-information opening messages commonly generated by the two
 * active research campaigns. This deliberately avoids an AI-generated feature
 * dump on the first turn and gives the client one low-effort question to answer.
 */
export function researchCampaignOpening(text: string, firstClientTurn: boolean): ResearchCampaignOpening | null {
  if (!firstClientTurn) return null;
  const clean = text.trim().replace(/\s+/g, " ");
  if (!clean || clean.length > 180 || OTHER_SERVICE.test(clean)) return null;

  if (SHORT_PRICE_ENQUIRY.test(clean) && clean.length <= 90) {
    return {
      serviceInterest: "Research enquiry",
      reply: "The *AI-Assisted Proposal Writing course is K350*. For hands-on research support, the fee depends on the task and deadline. Are you looking for the course, or help with your actual proposal or dissertation?"
    };
  }

  if (!VAGUE_AD_ENQUIRY.test(clean)) return null;

  return {
    serviceInterest: "Research enquiry",
    reply: "Absolutely. If you’re working on an actual proposal or dissertation, MedMinds can support you directly. We also have the *K350 AI-Assisted Proposal Writing course* if you prefer to learn the process yourself. What are you working on right now: a proposal, dissertation, or data analysis?"
  };
}
